name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
        run: docker build 
          --build-arg GIT_USERNAME=${GIT_USERNAME} 
          --build-arg GIT_PASSWORD=${GIT_PASSWORD} 
          -t sythilearn/entrypoint-service .

      - name: Push Docker image to Docker Hub
        run: docker push sythilearn/entrypoint-service

      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker rm -f entrypoint-service-container || true
            docker pull sythilearn/entrypoint-service
            docker run -d --name entrypoint-service-container -p 48003:48003 sythilearn/entrypoint-service

